name: Docker Image CI

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout git

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: moonnse
          password: muunuu123456

      - name: Build the Docker image
        run: docker build . --tag moonnse/logistic_front:latest

      - name: Push the Docker image
        run: docker push moonnse/logistic_front:latest
